# Generated by Django 4.1.3 on 2022-11-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='forget_password_token',
            new_name='forget_token',
        ),
    ]
