# Generated by Django 4.1.3 on 2022-11-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0006_rename_forget_password_token_profile_forget_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
